{% set name = "bayesbay" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bayesbay-{{ version }}.tar.gz
  sha256: e263b6fda2dc3573d46bbdea85a518fa765933dd6e927ed7f64bb49c22ede616

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - scipy >=1.9.0
    - matplotlib-base >=3.0.0
    - shapely >=2.0.0
    - joblib >=1.3.2

test:
  imports:
    - bayesbay
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fmagrini/bayes-bay
  summary: 'Generalized trans-dimensional and hierarchical MCMC in Python'
  description: |
    BayesBay is a user-friendly Python package for generalized trans-dimensional and hierarchical MCMC sampling.
  license: BSD-3-Clause
  license_file: LICENCE
  doc_url: https://bayes-bay.readthedocs.io/
  dev_url: https://github.com/fmagrini/bayes-bay

extra:
  recipe-maintainers:
    - fmagrini
    - jwhhh
